name: square

low_dim_obs_horizon: 2
img_obs_horizon: 2
action_horizon: 16

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      horizon: ${task.img_obs_horizon}
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      horizon: ${task.img_obs_horizon}
      type: rgb
    # robot0_eef_pos_abs:
    #   shape: [1]
    #   axis: [2] # 2 means z-axis
    #   horizon: ${task.low_dim_obs_horizon}
    #   type: low_dim
    # robot0_eef_quat_abs:
    #   shape: [2]
    #   axis: [0, 1] # raw and pitch
    #   horizon: ${task.low_dim_obs_horizon}
    #   type: low_dim
    robot0_eef_pos:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon}
      type: low_dim
    robot0_eef_quat:
      raw_shape: [4]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      type: low_dim
      rotation_rep: rotation_6d
    robot0_gripper_qpos:
      shape: [2]
      horizon: ${task.low_dim_obs_horizon}
      type: low_dim
  action:
    shape: [10]
    horizon: ${task.action_horizon}
    rotation_rep: rotation_6d
  render:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb

task_name: &task_name square
dataset_type: &dataset_type ph
dataset_path: &dataset_path data/robomimic/datasets/${task.task_name}/${task.dataset_type}/image_abs.hdf5
pose_repr: &pose_repr
  obs_pose_repr: abs # abs or rel
  action_pose_repr: abs

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_runner.RobomimicRunner
  dataset_path: *dataset_path
  pose_repr: *pose_repr
  shape_meta: *shape_meta
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  # use python's eval function as resolver, single-quoted string as argument
  max_steps: ${eval:'500 if "${task.dataset_type}" == "mh" else 400'}
  n_action_steps: ${n_action_steps}
  render_obs_key:
    - 'agentview_image'
    - 'robot0_eye_in_hand_image'
  fps: 10
  crf: 22
  tqdm_interval_sec: 1.0
  n_envs: 28
  obs_latency_steps: 0
# evaluation at this config requires a 16 core 64GB instance.

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_dataset.RobomimicReplayDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  pose_repr: *pose_repr
  temporally_independent_normalization: False
  seed: 42
  val_ratio: 0.02