name: real_image

image_shape: [3, 224, 224]
dataset_path: data/gopro_mug_10hz.zarr.zip

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    img:
      shape: ${task.image_shape}
      type: rgb
    robot_eef_pose:
      shape: [6]
      type: low_dim
    gripper_width:
      shape: [1]
      type: low_dim
  action: 
    shape: [10]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.umi_image_dataset.UmiImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${horizon}-${n_obs_steps}'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
